export interface Product {
    IDMon: number | 0 | string | '',
    IDLoaiMon: number | 0| string | '',
    DVTMon: string | '',
    Deleted: boolean,
    DonGiaBanLe: number | 0,
    DonGiaBanSi: number | 0,
    DonGiaVon: number | 0,
    GhiChu: string | '',
    Image: string | '',
    NgaySua: Date | null,
    NgayTao: Date | null,
    SoLuongTonKho: number | 0,
    TenMon: string | '',
    ThoiGianBH:  | null,
};