# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "pro" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn install --frozen-lockfile

    - name: Check if PM2 is installed
      run: |
        if ! command -v pm2 &> /dev/null
        then
            echo "PM2 could not be found, installing..."
            yarn global add pm2
        else
            echo "PM2 is already installed"
        fi

    - name: Start or Restart PM2 Application
      run: |
        pm2 list  # Hiển thị danh sách các ứng dụng hiện đang được quản lý bởi PM2 (để kiểm tra/debug)
        if pm2 describe api-smart-shop > /dev/null; then
          pm2 restart api-smart-shop
        else
          pm2 start yarn --interpreter bash --name "api-smart-shop" -- build:production
        fi
